import Foundation

/// Rust-backed `SleepEngineClientProtocol` implementation.
///
/// Under `SLEEPKIT_USE_RUST`:
///   - Holds an owned `FfiSleepEngine` generated by swift-bridge.
///   - Converts between Swift-native `Date`/`SleepStage`/`SessionSummary` and
///     the FFI types so callers never see `RustString` or `Ffi*`.
///   - Throws `SleepEngineError.underlying(_)` with the Rust error description
///     for every failure path; bridge-level details are never surfaced to
///     ViewModels.
///
/// Without the flag this class compiles as a throwing stub so existing call
/// sites that hold a `SleepEngineClientProtocol` reference still type-check.
///
/// This class is `@MainActor`-isolated. `swift-bridge` requires exclusive
/// `&mut self` on the Rust side for mutating calls; main-actor isolation
/// guarantees that without extra locks.
@MainActor
public final class RustSleepEngineClient: SleepEngineClientProtocol {

    private let dbPath: String
    private let modelPath: String
    private let userId: String

    #if SLEEPKIT_USE_RUST
    private var engine: FfiSleepEngine
    #endif

    public init(dbPath: String, modelPath: String = "", userId: String = "local-user") throws {
        self.dbPath = dbPath
        self.modelPath = modelPath
        self.userId = userId

        #if SLEEPKIT_USE_RUST
        let cfg = FfiEngineConfig(
            db_path: RustString(dbPath),
            model_path: RustString(modelPath),
            user_id: RustString(userId)
        )
        do {
            self.engine = try ffi_sleep_engine_new(cfg)
        } catch let e as RustString {
            throw SleepEngineError.underlying(e.toString())
        } catch {
            throw SleepEngineError.underlying(String(describing: error))
        }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func startSession(at date: Date) throws -> String {
        #if SLEEPKIT_USE_RUST
        do {
            return try engine.start_session(date.millis).toString()
        } catch let e as RustString {
            throw SleepEngineError.underlying(e.toString())
        } catch {
            throw SleepEngineError.underlying(String(describing: error))
        }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func endSession() throws -> SessionSummary {
        #if SLEEPKIT_USE_RUST
        do {
            let ffi = try engine.end_session()
            return SessionSummary(
                sessionId:      ffi.session_id.toString(),
                durationSec:    Int(ffi.duration_sec),
                timeInWakeSec:  Int(ffi.time_in_wake_sec),
                timeInLightSec: Int(ffi.time_in_light_sec),
                timeInDeepSec:  Int(ffi.time_in_deep_sec),
                timeInRemSec:   Int(ffi.time_in_rem_sec),
                sleepScore:     Int(ffi.sleep_score)
            )
        } catch let e as RustString {
            throw SleepEngineError.underlying(e.toString())
        } catch {
            throw SleepEngineError.underlying(String(describing: error))
        }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func pushHeartRate(_ bpm: Float, at date: Date) throws {
        #if SLEEPKIT_USE_RUST
        do { try engine.push_heart_rate(bpm, date.millis) }
        catch let e as RustString { throw SleepEngineError.underlying(e.toString()) }
        catch { throw SleepEngineError.underlying(String(describing: error)) }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func pushAccelerometer(x: Float, y: Float, z: Float, at date: Date) throws {
        #if SLEEPKIT_USE_RUST
        do { try engine.push_accelerometer(x, y, z, date.millis) }
        catch let e as RustString { throw SleepEngineError.underlying(e.toString()) }
        catch { throw SleepEngineError.underlying(String(describing: error)) }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func currentStage() throws -> SleepStage {
        #if SLEEPKIT_USE_RUST
        return SleepStage(rawValue: Int(engine.current_stage())) ?? .wake
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func currentConfidence() throws -> Float {
        #if SLEEPKIT_USE_RUST
        return engine.current_confidence()
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func armSmartAlarm(target: Date, windowMinutes: Int) throws {
        #if SLEEPKIT_USE_RUST
        let mins = UInt32(max(0, windowMinutes))
        do { try engine.arm_smart_alarm(target.millis, mins) }
        catch let e as RustString { throw SleepEngineError.underlying(e.toString()) }
        catch { throw SleepEngineError.underlying(String(describing: error)) }
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }

    public func checkAlarmTrigger(now: Date) throws -> Bool {
        #if SLEEPKIT_USE_RUST
        return engine.check_alarm_trigger(now.millis)
        #else
        throw SleepEngineError.engineUnavailable
        #endif
    }
}

private extension Date {
    /// Milliseconds since 1970, clamped to UInt64.
    var millis: UInt64 {
        let ms = timeIntervalSince1970 * 1000.0
        guard ms.isFinite, ms > 0 else { return 0 }
        return UInt64(ms)
    }
}
